Cargo.toml
src/channel/mod.rs
src/circle/bitcoin_script.rs
src/circle_secure/bitcoin_script.rs
src/circle_secure/mod.rs
src/lib.rs

This PR merges the wip in the oods-feature branch to prepare for a major refactoring.

Merge the wip in oods-feature: double_x, oods sampling

---

src/constraints/bitcoin_script.rs
src/constraints/mod.rs
src/lib.rs

This PR merges the wip pair vanishing. Soon, this can use stwo's dependency as a reference.

Include wip pair-vanishing

---

.github/workflows/test.yml
README.md

Setup Github Action workflow with the following steps:
- test: runs unit test (with `--nocapture` because for now it's how we measure efficiency of the scripts)
- clippy
- lint
- typos check

👷 setup CI

---

.github/workflows/test.yml
Cargo.toml
src/channel/bitcoin_script.rs
src/circle/bitcoin_script.rs
src/constraints/bitcoin_script.rs
src/fri/bitcoin_script.rs
src/lib.rs
src/merkle_tree/bitcoin_script.rs
src/oods/bitcoin_script.rs
src/pow/bitcoin_script.rs
src/tests_utils/mod.rs
src/tests_utils/report.rs

Generate a report to track the performance of the various Bitcoin scripts generated during the execution of tests.
- Create `test_utils/report` module to add utility functions to generate and manage a CSV report file
- Update tests to invoke the report function instead of printing
- Update the Test CI to upload the report as downloadable artifact
Example of generated file:

🧑‍💻 generate bitcoin script performance report during test execution instead of simple print

---

src/channel/bitcoin_script.rs
src/channel/mod.rs
src/fibonacci/mod.rs
src/fri/bitcoin_script.rs
src/oods/bitcoin_script.rs
src/oods/mod.rs

This PR finishes the refactoring the channel and start assembling a verifier that generates the hint as well as a data structure for hints.

Refactor the channel and add the global hinter

---

.github/workflows/test.yml

This PR tries to see if it is possible to let test.yml read-only.

Make test.yml read-only on the repository

---

.cargo-husky/hooks/pre-commit
Cargo.toml
README.md
src/air/bitcoin_script.rs
src/air/mod.rs
src/channel/bitcoin_script.rs
src/channel/mod.rs
src/circle/bitcoin_script.rs
src/constraints/bitcoin_script.rs
src/fibonacci/bitcoin_script/composition.rs
src/fibonacci/bitcoin_script/mod.rs
src/fibonacci/mod.rs
src/fri/bitcoin_script.rs
src/lib.rs
src/merkle_tree/bitcoin_script.rs
src/merkle_tree/mod.rs
src/oods/bitcoin_script.rs
src/oods/mod.rs
src/twiddle_merkle_tree/bitcoin_script.rs
src/twiddle_merkle_tree/mod.rs
src/utils/mod.rs

This PR made a few optimization as well as kickstarted the end-to-end implementation of a verifier.
- many "push_" functions in the gadgets have been moved into the Pushable trait. Now, one can simply push it.
- finish most of the components of a verifier, except the part for checking commitment opening and FRI.

Some progress on verifier

---

src/fibonacci/bitcoin_script/mod.rs
src/fibonacci/mod.rs

This is a PR that removes some data after they are no longer used. Moreover, it adds the computation of line coefficients in the verifier script.

Simplify the stack and compute line coefficients

---

src/fibonacci/bitcoin_script/mod.rs
src/fibonacci/mod.rs

This PR adds the computation of line coefficients in the verifier script.

Compute line coeffs

---

src/constraints/bitcoin_script.rs
src/constraints/mod.rs
src/fibonacci/bitcoin_script/mod.rs
src/fibonacci/mod.rs

This PR computes the nominators for the first query point. The next step is to apply random coeffs to it as well as multiply with the denominators.

Compute the nominators

---

Cargo.toml
src/air/mod.rs
src/fibonacci/bitcoin_script/fiat_shamir.rs
src/fibonacci/bitcoin_script/mod.rs
src/fibonacci/fiat_shamir.rs
src/fibonacci/mod.rs
src/fri/bitcoin_script.rs
src/fri/mod.rs
src/oods/mod.rs
src/pow/mod.rs

This PR now is able to compute the FRI answers. We have code that checks its consistency with the stwo implementation.
The next step is to implement the folding.

Compute the FRI answers

---

src/fibonacci/mod.rs
src/fibonacci/utils.rs

this PR focus on generating Fiat Shamir hints, and providing inputs for fri hints following behind

Generate Fiat Shamir hints along with FRI inputs

---

src/fibonacci/mod.rs
src/fibonacci/prepare.rs

this PR focus on separating the middle part between Fiat Shamir hints and quotient hints

Split logic for the middle part between Fiat Shamir and quotient

---

src/fibonacci/bitcoin_script/mod.rs
src/fibonacci/bitcoin_script/quotients.rs
src/fibonacci/mod.rs
src/fibonacci/quotients.rs

This PR moves the code related to per-query quotient into a separate file.

Move per-query quotient into a separate file

---

src/fibonacci/bitcoin_script/mod.rs
src/fibonacci/bitcoin_script/prepare.rs
src/fibonacci/mod.rs
src/fibonacci/prepare.rs

this PR focus on separating prepare scripts

Split logic for prepare scripts

---

src/fibonacci/bitcoin_script/quotients.rs
src/fibonacci/fiat_shamir.rs
src/fibonacci/fold.rs
src/fibonacci/mod.rs
src/fibonacci/prepare.rs
src/fibonacci/quotients.rs
src/fri/bitcoin_script.rs
src/fri/mod.rs

This PR presents some progress in folding. The non-Bitcoin-script side of the code is already able to reproduce STARK verification (checking that the last layer evaluation is the same).

Progress in folding

---

src/fibonacci/fold.rs

This PR generates the Merkle tree hints that are necessary for the prover to understand the FRI.
A corresponding Bitcoin script should be in a forthcoming PR.

Generate Merkle tree hints for intermediate FRI steps

---

Cargo.toml
src/air/mod.rs
src/constraints/mod.rs
src/fibonacci/bitcoin_script/fold.rs
src/fibonacci/bitcoin_script/mod.rs
src/fibonacci/bitcoin_script/prepare.rs
src/fibonacci/fiat_shamir.rs
src/fibonacci/fold.rs
src/fibonacci/mod.rs
src/fibonacci/prepare.rs
src/fibonacci/quotients.rs
src/fibonacci/split/mod.rs
src/lib.rs
src/pow/mod.rs
src/utils/bitcoin_script.rs

This PR splits the verifier into smaller transaction and uses the Bitcoin simulator to simulate transactions that handle it.
The program will read a proof (in 10 steps) and after accepting the proof, it resets itself to be ready to accept another proof.

Split the program

---

src/channel/bitcoin_script.rs
src/channel/mod.rs
src/lib.rs
src/merkle_tree/mod.rs
src/oods/bitcoin_script.rs
src/pow/bitcoin_script.rs
src/pow/mod.rs

The stwo fork has some updates, and the changes are incorporated here.

Update the implementation to follow the latest stwo fork

---

Cargo.lock
src/dsl/plonk/covenant.rs
src/dsl/plonk/mod.rs

Update the Cargo.toml to use the simplified LDM construction

Update Cargo.lock with the new hash construction

---

.gitignore
Cargo.lock
Cargo.toml
src/bin/demo.rs
src/bin/gen_demo_params.rs
src/tests_utils/report.rs

- add useful logs
- dynamic parameters like initial randomizer, funding tx vout

Improved demo binary
